### ISSUE TITLE
Rewards

### ISSUE THREAD

**Issue by cawabunga** [solid-world/solid-world-dao-contracts#129]
## Epic

We need to implement a mechanism that rewards liquidity providers (stakeholders that provide liquidity for our
collateralized basket token liquidity pools)

## Solution

We'll inspire from [Aave rewards mechanism](https://github.com/aave/aave-v3-periphery/tree/master/docs/rewards).

[Here](https://www.figma.com/file/aMkir6iiOwIFlrccamtKD2/Rewards-contract-research?node-id=45%3A183)'s a Figma diagram by @AWTammsaar explaining how different moving parts work together.

An explanation on how rewards distribution works under the hood can be found [here](https://docs.google.com/spreadsheets/d/1KNP36ry0mn4kTSnOlHYRympV3x-44Qn-g48POmNcXVM/edit#gid=0).

### 1. User interaction with liquidity pools. Becoming a liquidity provider.

✅ This part is for enabling users holding a collateralized basket token to become liquidity providers.

We’ll use [Gamma](https://www.gamma.xyz/) contracts for interacting with Uniswap V3 pools, **after the pools are created**.
We are using it because it provides fungible liquidity to Uniswap V3 (vanilla Uniswap V3 pools offer NFT LP tokens)

- [Hypervisor](https://github.com/GammaStrategies/hypervisor/blob/master/contracts/Hypervisor.sol)
  - encapsulates deposit & withdraw logic for working with Uniswap V3 pools
  - users can withdraw funds by calling `withdraw(shares, to, from, minAmounts)`
- [UniProxy](https://github.com/GammaStrategies/hypervisor/blob/master/contracts/UniProxy.sol)
  - manages deposits into all Hypervisors
  - we can call `getDepositAmount(hypervisor, token0, deposit)` to get the amount of `token1` that user needs to deposit to become LP
  - we call `deposit(deposit0, deposit1, to, hypervisor, minIn)` that calls `deposit` on right Hypervisor that deposits into a Uniswap V3 pool

Using those ↑, users get their hands on LP tokens that are stake-able into our staking contract.
By staking LP tokens into our staking contract, LPs enter our rewarding mechanism and start accruing various weekly rewards.

#### Production dependencies:

- functional collateralization process
- at least one Uniswap V3 pool created
- a Hypervisor contract deployed
  - can be deployed via a transaction to the HypervisorFactory
  - can be deployed via Gamma UI (? to be checked)

#### Tasks (to be refined):

- [ ] Implement feature to allow users to become liquidity providers (deposit into Uniswap V3 pools via Gamma)
  - [ ] Create UI for users to deposit their various ERC20 tokens into Uniswap V3 pools
  - [ ] Implement logic to fetch and display user's current position (erc20 tokens owned and balances, owned LP tokens)
  - [ ] Implement logic for taking user's deposit token & amount and depositing into Uniswap V3 pool via Gamma (sending transaction, providing user feedback on transaction status)
- [ ] Implement feature to allow users to withdraw their liquidity (withdraw from Uniswap V3 pools via Gamma)
  - [ ] Create UI for users to withdraw their various ERC20 tokens from Uniswap V3 pools
  - [ ] Reuse logic from deposit feature to fetch and display user's current position
  - [ ] Implement logic for taking user's withdraw amount and withdrawing from Uniswap V3 pool via Gamma (sending transaction, providing user feedback on transaction status)
- [ ] We need to have a (dummy) contract - `SolidHypervisorAdaptor` - that exposes following functions to be able to test the UI:
  - [ ] getUserBalances() that returns (categoryId, erc20Balance, lpTokenBalance)[] for a given user (we could also use a subgraph for this, more complicated)
    - need to iterate over categoryIds, call `SolidWorldManager` to get the ERC20 then `balanceOf`, and call `Hypervisor.balanceOf` to get lpToken balance
  - [ ] getRequiredDepositAmount(categoryId, token0, token0Deposit) → returns amount of token1 that user needs to deposit into Uniswap V3 pool corresponding to categoryId (via UniProxy)
  - [ ] deposit(categoryId, deposit0, deposit1) → calls deposit on UniProxy that calls deposit on right Hypervisor that deposits into a Uniswap V3 pool corresponding to categoryId
    - user needs to approve UniProxy to spend deposit0 and deposit1 tokens
  - [ ] withdraw(categoryId, lpTokens) → calls withdraw on the right Hypervisor that withdraws from a Uniswap V3 pool corresponding to categoryId
  - [ ] `SolidHypervisorAdaptor` will work with the interfaces for Hypervisor and UniProxy
  - [ ] `SolidHypervisorAdaptor` needs to hold one IUniProxy and a map for categoryId => IHypervisor
  - [ ] `SolidHypervisorAdaptor` needs to allow the admin to add new elements to the categoryId => IHypervisor map
  - [ ] UniProxy holds an array of Hypervisors, only admin can add new Hypervisors to the array
  - [ ] on local & testnet we can deploy ourselves the UniProxy, Hypervisors and Uniswap V3 pools
    - [ ] to deploy Uniswap V3 locally, we can use [this](https://github.com/Uniswap/hardhat-v3-deploy)
  - [ ] on mainnet we may need to reach out to Gamma team to get Hypervisors deployed for our pools and officially supported by them

_Users may provide liquidity directly via Gamma webapp._

### 2. Staking

✅ This part is for enabling liquidity providers to stake their LP tokens and start accruing rewards.

We can inspire from [StakingRewards](https://github.com/Synthetixio/synthetix/blob/develop/contracts/StakingRewards.sol) contract.

The staking contract will accept deposits of various LP tokens from users and interact with the rewards mechanism.
The contract will also expose methods that fetch the user's current position & stats.

#### Dependencies:

- to actually test the staking contract, we'd ideally have the mechanism to become LP implemented

#### Tasks (to be refined):

- [ ] Implement feature to allow users to stake their various LP tokens
  - [ ] Create dummy UI for users to stake their various LP tokens
  - [ ] Implement logic to fetch and display user's current position (LP tokens available, LP tokens staked, APR, TVL, etc.)
  - [ ] Implement logic for taking user's chosen stake token & amount and staking into our staking contract (sending transaction, providing user feedback on transaction status)
- [ ] Implement feature to allow users to withdraw their staked LP tokens
  - [ ] Create dummy UI for users to withdraw their staked LP tokens
  - [ ] Reuse logic from deposit feature to fetch and display user's current position
  - [ ] Implement logic for taking user's chosen stake token & amount and withdrawing from our staking contract (sending transaction, providing user feedback on transaction status)
- [x] Create a StakingRewards contract and make some changes to it:
  - [x] Add support for staking various types of assets (different LP tokens). Currently, it only supports one staking token.
    - [x] instead of `stake(amount)`, we'll have `stake(lpTokenAddress, amount)`
    - [x] instead of `withdraw(amount)`, we'll have `withdraw(lpTokenAddress, amount)`
    - [x] instead of `balanceOf(account)`, we'll have `balanceOf(lpTokenAddress, account)`
    - [ ] instead of `totalSupply()`, we'll have `totalSupply(lpTokenAddres)`
    - [ ] instead of `earned(account)`, we'll have `earned(lpTokenAddress, account)`
    - [x] we need a function to add support for new LP tokens
    - [x] we need to be able to iterate over all supported LP tokens
    - [x] we need a function to fetch stats for a given LP token
- [x] Add support to dynamically change reward rates, so we could adjust carbon-side (time appreciation) rewards weekly
  - [x] each time a user (un)stakes an asset, the staking contract will call `handleAction(user, userBalance, totalSupply)` on `RewardsController` (detailed in part 3)
- [x] Add support to give multiple different rewards. We would like to also subsidize with governance token and USDC
  - [x] we can probably remove reward logic completely from the staking contract, and delegate this to Aave's rewards mechanism

### 3. Rewards mechanism

✅ This part is for enabling LPs to accrue rewards in an elegant and efficient way, and providing LPs a way to claim their rewards.

We'll inspire from [Aave rewards mechanism](https://github.com/aave/aave-v3-periphery/tree/master/docs/rewards).

Rewards must be ERC20 compatible contracts that expose the "decimals" function. We'll offer different reward types for LPs:
- Carbon-side rewards (coming from time appreciation)
  - e.g. LPs for Mangrove Uniswap Pool accrue weekly rewards in the form of mangrove-FCB ERC20 tokens
- USDC rewards (coming from ... ?)
  - e.g. LPs for certain pools accrue weekly rewards in the form of USDC
- Governance token rewards (we can mint new governance tokens and distribute them to LPs)
  - e.g. LPs for certain pools accrue weekly rewards in the form of Solid governance tokens

Main contracts:
- RewardsDistributor
  - does the accounting of rewards (keeps track of how much each LP has accrued so far and global rewards state)
- RewardsController
  - expose functions for users to claim their rewards (all or part of it), configure different aspects of the rewards mechanism
  - `RewardsController` inherits from `RewardsDistributor`
  - receives `EmissionManager` in constructor
- EmissionsManager
  - manages the list of admins per reward type (i.e. each reward type has its own set of admins that can call incentives-mutating functions)
  - receives `RewardsController` in constructor... but the `EmissionsManager` must be deployed first, and then the `RewardsController`, and then in the `EmissionsManager` set the `RewardsController` via `setRewardsController`

We need a UI element for users to claim their rewards.
The `claim rewards` flow here is represented [here](https://github.com/aave/aave-v3-periphery/raw/master/docs/rewards/img/ClaimFlow.png).

We'll also need to automate calling a function on a weekly basis. The function will:
- be part of `SolidWorldManager` contract (.. ?)
- iterate over all ERC1155 tokens, and for each that needs repricing:
  - compute & mint the appropriate amount of ERC20 tokens based on BV difference to the correct REWARDS_VAULT
    - BV difference = FCBT.balanceOf(SolidWorldManager, categoryId) * ((1- tApprec)**(weeksTillCert - 1) - (1- tApprec)**weeksTillCert)
- then call `RewardsController.setEmissionsPerSecond` & `RewardsController.setDistributionEnd`

#### Dependencies:

- to properly test the rewards mechanism, we'd ideally have the staking part implemented

#### Tasks (to be refined):

- [x] Implement RewardsController, EmissionsManager
- [x] Connect staking contract with rewards mechanism
- [ ] Implement UI for users to claim their rewards
- [ ] Implement the function that mints & distributes rewards
- [ ] Automate calling the function that mints & distributes rewards on a weekly basis
